name: Update Neovim Submodule

on:
  repository_dispatch:
    types: [update-nvim]

jobs:
  updateSubmodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update Submodule
        run: |
          git submodule update --remote --force

      - name: Commit Submodule Update
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore(nvim): update submodule"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
